# Generated by Django 5.0.14 on 2026-07-05 09:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('resume_score', models.IntegerField(blank=True, null=True)),
                ('average_interview_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('skill_strengths', models.JSONField(default=list)),
                ('skill_weaknesses', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Progress histories',
            },
        ),
    ]
